<a href="https://colab.research.google.com/github/JuliaZyrianova/imdb-movies-eda/blob/main/%22%D0%9F%D1%80%D0%B5%D0%B4%D0%BE%D0%B1%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%B0_%D0%B8_%D0%9E%D1%87%D0%B8%D1%81%D1%82%D0%BA%D0%B0%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Разведочный анализ по датасету IMDb Movies: 5000 фильмов с наибольшим рейтингом. Часть 1: Обзор и предобработка данных**

## 1. Описание датасета и задания

Представлен датасет с данными о 5000 фильмах, имеющих наибольший рейтинг на сайте IMDb (датасет выложен на платформе [Kaggle](https://www.kaggle.com/datasets/totoro29/imdb-movies)).

***Информация, содержащаяся в датасете:***
1.   Ссылка на постер фильма (poster).
2.   Наименование фильма (title).
3.   Класс фильма по рейтингу the British Board of Film Classification (BBFC) (certificate).
4.   Продолжительность фильма (runtime).
5.   Жанр фильма (genre).
6.   Рейтинг фильма на платформе IMBD (rating).
7.   Описание сюжета фильма (about).
8.   Кинорежиссер фильма (director).
9.   Актеры-звезды фильма (stars).
10.  Количество проголосовавших за фильм (votes).
11.  Доход с фильма (gross_earn).

***Задача:***
провести разведочный анализ данных, найти взаимосвязи и сформулировать выводы.

**В части 1 задания необходимо:**
1.   Выполнить обзор данных.
2.   Оценить датасет на наличие дубликатов и при необходимости обработать их.
3.   Оценить признаки на наличие пропусков и при необходимости обработать их.
4.   Привести данные к необходимому для анализа типу.
5.   Отсортировать и сохранить датасет для дальнейшего анализа.

## 2. Загрузка датасета

In [1]:
!pip install --upgrade gdown

Requirement already satisfied: gdown in /usr/local/lib/python3.13/dist-packages (6.1.0)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.13/dist-packages (from gdown) (4.13.5)
Requirement already satisfied: filelock in /usr/local/lib/python3.13/dist-packages (from gdown) (3.32.4)
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.13/dist-packages (from gdown) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (from gdown) (4.67.3)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.13/dist-packages (from beautifulsoup4->gdown) (2.9.2)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.13/dist-packages (from beautifulsoup4->gdown) (4.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests[socks]->gdown) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests[socks]->gdown) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests[socks]->gdown) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests[socks]->gdown) (2026.7.22)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.13/dist-packages (from requests[socks]->gdown) (1.7.1)

In [6]:
!gdown 1XhsLqwdR1a6xBRTOJ8JUfbgvL7YDTSH6

Downloading...
From: https://drive.google.com/uc?id=1XhsLqwdR1a6xBRTOJ8JUfbgvL7YDTSH6
To: /content/movies.csv
100% 1.89M/1.89M [00:00<00:00, 155MB/s]

## 3. Подгрузка данных в питон и начало работы с ними

In [7]:
import pandas as pd

In [8]:
dataset = pd.read_csv('movies.csv')

In [9]:
dataset.head()

,poster,title,certificate,runtime,genre,rating,about,director,stars,votes,gross_earn
0,https://m.media-amazon.com/images/S/sash/4Fyxw...,The Shawshank Redemption,15,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,Frank Darabont,"('Tim Robbins',), ('Morgan Freeman',), ('Bob G...","26,26,905",$28.34M
1,https://m.media-amazon.com/images/S/sash/4Fyxw...,The Dark Knight,12A,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,Christopher Nolan,"('Christian Bale',), ('Heath Ledger',), ('Aaro...","25,98,173",$534.86M
2,https://m.media-amazon.com/images/S/sash/4Fyxw...,Inception,12A,148 min,"Action, Adventure, Sci-Fi",8.8,A thief who steals corporate secrets through t...,Christopher Nolan,"('Leonardo DiCaprio',), ('Joseph Gordon-Levitt...","23,04,062",$292.58M
3,https://m.media-amazon.com/images/S/sash/4Fyxw...,Fight Club,18,139 min,Drama,8.8,An insomniac office worker and a devil-may-car...,David Fincher,"('Brad Pitt',), ('Edward Norton',), ('Meat Loa...","20,71,088",$37.03M
4,https://m.media-amazon.com/images/S/sash/4Fyxw...,Pulp Fiction,18,154 min,"Crime, Drama",8.9,"The lives of two mob hitmen, a boxer, a gangst...",Quentin Tarantino,"('John Travolta',), ('Uma Thurman',), ('Samuel...","20,11,013",$107.93M

## 4. Оценка размеров датасета, наличия дубликатов и пропусков

In [10]:
dataset.shape

(5000, 11)

In [11]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   poster       5000 non-null   object
 1   title        5000 non-null   object
 2   certificate  5000 non-null   object
 3   runtime      5000 non-null   object
 4   genre        4970 non-null   object
 5   rating       5000 non-null   float64
 6   about        4986 non-null   object
 7   director     5000 non-null   object
 8   stars        5000 non-null   object
 9   votes        5000 non-null   object
 10  gross_earn   4585 non-null   object
dtypes: float64(1), object(10)
memory usage: 429.8+ KB

Оцениваем наличие дубликатов в датасете

In [12]:
dataset.duplicated().sum()

np.int64(0)

Оцениваем наличие пропущенных значений в датасете по признаку gross_earn

In [13]:
dataset['gross_earn'].isna().mean()*100

np.float64(8.3)

 На этапе предобработки датасета не буду исключать наблюдения с пропущенными значениями, так как нет жесткого требования это делать. Можно потерять информацию по другим более значимым признакам. Кроме того, их наличие может нести ценную информацию при анализе.

## 5. Обработка колонок runtime и gross_earn: приведение к числовому типу

### *5.1. runtime*

In [14]:
dataset['runtime']

0              142 min
1              152 min
2              148 min
3              139 min
4              154 min
             ...
4995           102 min
4996            94 min
4997    Drama, Romance
4998            92 min
4999           120 min
Name: runtime, Length: 5000, dtype: object

По индексу 4997 в признак попало аномальное значение - Drama, Romance

In [15]:
dataset['runtime'].unique()

array(['142 min', '152 min', '148 min', '139 min', '154 min', '178 min',
       '136 min', '201 min', '175 min', '164 min', '179 min', '127 min',
       '143 min', '155 min', '140 min', '165 min', '169 min', '121 min',
       '118 min', '162 min', '153 min', '151 min', '195 min', '113 min',
       '130 min', '124 min', '122 min', '194 min', '132 min', '202 min',
       '138 min', '119 min', '189 min', '180 min', '137 min', '106 min',
       '111 min', '116 min', '145 min', '110 min', '98 min', '107 min',
       '126 min', '100 min', '131 min', '133 min', '103 min', '108 min',
       '96 min', '99 min', '115 min', '88 min', '120 min', '81 min',
       '135 min', '146 min', '117 min', '104 min', '92 min', '91 min',
       '102 min', '149 min', '170 min', '112 min', '101 min', '141 min',
       '144 min', '114 min', '150 min', '90 min', '161 min', '128 min',
       '93 min', '129 min', '166 min', '147 min', '134 min', '109 min',
       '105 min', '125 min', '156 min', '123 min', '95 min', '157 min',
       '163 min', '158 min', '89 min', '187 min', '167 min', '84 min',
       '94 min', '85 min', '172 min', '160 min', '168 min', '86 min',
       '97 min', '87 min', '183 min', '188 min', '207 min', '159 min',
       '76 min', '229 min', '238 min', '83 min', '218 min', '77 min',
       '181 min', '191 min', '80 min', '212 min', '78 min', '79 min',
       '82 min', '74 min', '185 min', '75 min', '197 min', '69 min',
       '64 min', '224 min', '68 min', '210 min', '177 min', '193 min',
       '67 min', '174 min', '70 min', '220 min', '321 min', 'Comedy',
       '186 min', 'Action, Crime, Mystery', '198 min', '58 min',
       'Comedy, Drama, Romance', 'Comedy, Romance', '192 min', '242 min',
       'Horror', '204 min', 'Comedy, Drama', '171 min', '63 min',
       'Horror, Sci-Fi, Thriller', 'Action, Biography, Drama', '182 min',
       '176 min', '196 min', 'Drama', '205 min', 'Action, Drama, War',
       '71 min', '259 min', '45 min', 'Fantasy, Romance',
       'Action, Crime, Comedy', 'Crime, Drama, Mystery',
       'Action, Adventure, Drama', 'Drama, Horror, Mystery',
       'Crime, Mystery', '213 min', '72 min', '216 min',
       'Comedy, Western', '317 min', 'Adventure, Drama, Romance',
       'Fantasy, Horror', 'Adventure, Comedy', 'Comedy, Family',
       'Adventure, Comedy, Romance', '366 min', 'Action, Comedy',
       'Adventure, Comedy, Fantasy', 'Action, Crime, Thriller',
       'Action, Adventure, Sci-Fi', 'Drama, Romance'], dtype=object)

Таких аномальных значений несколько. Следует исключить их из датасета

In [16]:
import re

In [17]:
def clear_runtime(runtime):
  return re.sub('\D','', runtime)

<>:2: SyntaxWarning: invalid escape sequence '\D'
<>:2: SyntaxWarning: invalid escape sequence '\D'
/tmp/ipykernel_3807/3415774863.py:2: SyntaxWarning: invalid escape sequence '\D'
  return re.sub('\D','', runtime)

In [18]:
dataset['runtime'].apply(clear_runtime)

0       142
1       152
2       148
3       139
4       154
       ...
4995    102
4996     94
4997
4998     92
4999    120
Name: runtime, Length: 5000, dtype: object

In [19]:
dataset['runtime_clear'] =dataset['runtime'].apply(clear_runtime)

In [20]:
dataset['runtime_clear']

0       142
1       152
2       148
3       139
4       154
       ...
4995    102
4996     94
4997
4998     92
4999    120
Name: runtime_clear, Length: 5000, dtype: object

In [21]:
dataset['runtime_clear'].isna().sum()

np.int64(0)

In [22]:
dataset['runtime_clear'][4997]

''

In [23]:
type(dataset['runtime_clear'][4997])

str

In [24]:
dataset = dataset[dataset['runtime_clear']!='']

In [25]:
dataset.shape

(4970, 12)

In [26]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4970 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   poster         4970 non-null   object
 1   title          4970 non-null   object
 2   certificate    4970 non-null   object
 3   runtime        4970 non-null   object
 4   genre          4970 non-null   object
 5   rating         4970 non-null   float64
 6   about          4956 non-null   object
 7   director       4970 non-null   object
 8   stars          4970 non-null   object
 9   votes          4970 non-null   object
 10  gross_earn     4574 non-null   object
 11  runtime_clear  4970 non-null   object
dtypes: float64(1), object(11)
memory usage: 504.8+ KB

In [27]:
dataset['runtime_clear'] = dataset.runtime_clear.astype('int')

In [28]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4970 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   poster         4970 non-null   object
 1   title          4970 non-null   object
 2   certificate    4970 non-null   object
 3   runtime        4970 non-null   object
 4   genre          4970 non-null   object
 5   rating         4970 non-null   float64
 6   about          4956 non-null   object
 7   director       4970 non-null   object
 8   stars          4970 non-null   object
 9   votes          4970 non-null   object
 10  gross_earn     4574 non-null   object
 11  runtime_clear  4970 non-null   int64
dtypes: float64(1), int64(1), object(10)
memory usage: 504.8+ KB

### *5.2. gross_earn*

In [30]:
dataset['gross_earn']

0        $28.34M
1       $534.86M
2       $292.58M
3        $37.03M
4       $107.93M
          ...
4994         NaN
4995      $9.40M
4996         NaN
4998      $6.67M
4999      $8.20M
Name: gross_earn, Length: 4970, dtype: object

In [34]:
def clear_gross_earn(gross_earn):
  return re.sub('[^\d\.]','', gross_earn)

<>:2: SyntaxWarning: invalid escape sequence '\d'
<>:2: SyntaxWarning: invalid escape sequence '\d'
/tmp/ipykernel_3807/2782825174.py:2: SyntaxWarning: invalid escape sequence '\d'
  return re.sub('[^\d\.]','', gross_earn)

In [35]:
dataset['gross_earn'].apply(clear_gross_earn)

TypeError: expected string or bytes-like object, got 'float'

Ошибка TypeError, связанная с тем, что в какой-то момент в функцию попали пропущенные значения, которые она не смогла обработать

In [36]:
dataset['gross_earn'].isna().sum()

np.int64(396)

In [37]:
import numpy as np

In [38]:
def clear_gross_earn(gross_earn):
  if pd.isna(gross_earn):
    return np.nan
  else:
    return re.sub('[^\d\.]', '', gross_earn)

<>:5: SyntaxWarning: invalid escape sequence '\d'
<>:5: SyntaxWarning: invalid escape sequence '\d'
/tmp/ipykernel_3807/1859203611.py:5: SyntaxWarning: invalid escape sequence '\d'
  return re.sub('[^\d\.]', '', gross_earn)

In [39]:
dataset['gross_earn'].apply(clear_gross_earn)

0        28.34
1       534.86
2       292.58
3        37.03
4       107.93
         ...
4994       NaN
4995      9.40
4996       NaN
4998      6.67
4999      8.20
Name: gross_earn, Length: 4970, dtype: object

In [40]:
dataset['gross_earn_clear'] = dataset['gross_earn'].apply(clear_gross_earn)

In [41]:
dataset['gross_earn_clear']

0        28.34
1       534.86
2       292.58
3        37.03
4       107.93
         ...
4994       NaN
4995      9.40
4996       NaN
4998      6.67
4999      8.20
Name: gross_earn_clear, Length: 4970, dtype: object

In [42]:
dataset['gross_earn_clear']= dataset.gross_earn_clear.astype('float')

In [43]:
dataset['gross_earn_clear']

0        28.34
1       534.86
2       292.58
3        37.03
4       107.93
         ...
4994       NaN
4995      9.40
4996       NaN
4998      6.67
4999      8.20
Name: gross_earn_clear, Length: 4970, dtype: float64

In [45]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4970 entries, 0 to 4999
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   poster            4970 non-null   object
 1   title             4970 non-null   object
 2   certificate       4970 non-null   object
 3   runtime           4970 non-null   object
 4   genre             4970 non-null   object
 5   rating            4970 non-null   float64
 6   about             4956 non-null   object
 7   director          4970 non-null   object
 8   stars             4970 non-null   object
 9   votes             4970 non-null   object
 10  gross_earn        4574 non-null   object
 11  runtime_clear     4970 non-null   int64
 12  gross_earn_clear  4574 non-null   float64
dtypes: float64(2), int64(1), object(10)
memory usage: 543.6+ KB

## 6. Сортировка по рейтингу

In [46]:
sorted_dataset =dataset.sort_values(by='rating', ascending=False)
sorted_dataset.head()

,poster,title,certificate,runtime,genre,rating,about,director,stars,votes,gross_earn,runtime_clear,gross_earn_clear
0,https://m.media-amazon.com/images/S/sash/4Fyxw...,The Shawshank Redemption,15,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,Frank Darabont,"('Tim Robbins',), ('Morgan Freeman',), ('Bob G...","26,26,905",$28.34M,142,28.34
9,https://m.media-amazon.com/images/S/sash/4Fyxw...,The Godfather,X,175 min,"Crime, Drama",9.2,The aging patriarch of an organized crime dyna...,Francis Ford Coppola,"('Marlon Brando',), ('Al Pacino',), ('James Ca...","18,19,641",$134.97M,175,134.97
3788,https://m.media-amazon.com/images/S/sash/4Fyxw...,Hababam Sinifi,12A,87 min,"Comedy, Drama",9.2,"Lazy, uneducated students share a very close b...",Ertem Egilmez,"('Kemal Sunal',), ('Münir Özkul',), ('Halit Ak...","40,492",NaN,87,NaN
8,https://m.media-amazon.com/images/S/sash/4Fyxw...,The Lord of the Rings: The Return of the King,12A,201 min,"Action, Adventure, Drama",9.0,Gandalf and Aragorn lead the World of Men agai...,Peter Jackson,"('Elijah Wood',), ('Viggo Mortensen',), ('Ian ...","18,01,662",$377.85M,201,377.85
24,https://m.media-amazon.com/images/S/sash/4Fyxw...,Schindler's List,15,195 min,"Biography, Drama, History",9.0,"In German-occupied Poland during World War II,...",Steven Spielberg,"('Liam Neeson',), ('Ralph Fiennes',), ('Ben Ki...","13,33,407",$96.90M,195,96.90

## 7. Переопределение индексов

In [47]:
sorted_dataset.reset_index(drop=True, inplace=True)
sorted_dataset.head()

,poster,title,certificate,runtime,genre,rating,about,director,stars,votes,gross_earn,runtime_clear,gross_earn_clear
0,https://m.media-amazon.com/images/S/sash/4Fyxw...,The Shawshank Redemption,15,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,Frank Darabont,"('Tim Robbins',), ('Morgan Freeman',), ('Bob G...","26,26,905",$28.34M,142,28.34
1,https://m.media-amazon.com/images/S/sash/4Fyxw...,The Godfather,X,175 min,"Crime, Drama",9.2,The aging patriarch of an organized crime dyna...,Francis Ford Coppola,"('Marlon Brando',), ('Al Pacino',), ('James Ca...","18,19,641",$134.97M,175,134.97
2,https://m.media-amazon.com/images/S/sash/4Fyxw...,Hababam Sinifi,12A,87 min,"Comedy, Drama",9.2,"Lazy, uneducated students share a very close b...",Ertem Egilmez,"('Kemal Sunal',), ('Münir Özkul',), ('Halit Ak...","40,492",NaN,87,NaN
3,https://m.media-amazon.com/images/S/sash/4Fyxw...,The Lord of the Rings: The Return of the King,12A,201 min,"Action, Adventure, Drama",9.0,Gandalf and Aragorn lead the World of Men agai...,Peter Jackson,"('Elijah Wood',), ('Viggo Mortensen',), ('Ian ...","18,01,662",$377.85M,201,377.85
4,https://m.media-amazon.com/images/S/sash/4Fyxw...,Schindler's List,15,195 min,"Biography, Drama, History",9.0,"In German-occupied Poland during World War II,...",Steven Spielberg,"('Liam Neeson',), ('Ralph Fiennes',), ('Ben Ki...","13,33,407",$96.90M,195,96.90

## 8. Сохранение датасета

In [48]:
sorted_dataset.to_csv('movies_clean.csv')